### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by KtorZ**
**[v0.10]**
- Fix minor typo in cloud code
- Trigger 'notificationreceive' when the app is in background but not killed.

### CODE REVIEW

**Comment by jvandijk** [comment]
@KtorZ why are you removing old distributable versions? By doing this you render libraries that depend on a certain version useless.
Please leave all versions in version control to be able to resolve these dependencies.

**Comment by KtorZ** [comment]
No, I don't. We are on Git. If someone need to access an older distributable version, he could just `git checkout xxx`. All labels refer to a commit, and it's really easy to get what you need. 
We don't need to pollute the most recent version with the old ones :/

**Comment by timanrebel** [comment]
Ideally we would tag all releases and upload the zip there. Let me do that after merging

**Comment by jvandijk** [comment]
@KtorZ you are absolutely right.... as long as @timanrebel really creates the tags! :smiley:

**Pull request merged**
